import {useState} from "react";
import {Cloud,LockKeyhole} from "lucide-react";
import {useTranslation} from "react-i18next";
import type {useAccountSync} from "../lib/useAccountSync";

type Account=ReturnType<typeof useAccountSync>;
export function LoginPage({account,onLocal}:{account:Account;onLocal:()=>void}){
  const {t}=useTranslation();const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
  async function run(action:()=>Promise<unknown>,success:string){setBusy(true);setMessage("");try{await action();setMessage(t(success))}catch(error){setMessage(error instanceof Error?error.message:t("account.failed"))}finally{setBusy(false)}}
  return <main className="login-page"><section className="login-card"><div className="login-brand"><img src="/paper-gacha-app-icon.png" alt=""/><span><strong>{t("brand")}</strong><small>{t("tagline")}</small></span></div><div className="login-heading"><span className="login-icon"><Cloud size={25}/></span><h1>{t("account.welcome")}</h1><p>{t("account.welcomeDescription")}</p></div><button className="google-login" disabled={busy} onClick={account.google}>{t("account.google")}</button><div className="login-divider"><span>{t("account.orEmail")}</span></div><div className="login-fields"><label>{t("account.email")}<input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>{t("account.password")}<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label></div><div className="login-actions"><button className="primary" disabled={busy||!email||!password} onClick={()=>void run(()=>account.login(email,password),"account.loginSuccess")}><LockKeyhole size={17}/>{t("account.login")}</button><button disabled={busy||!email||!password} onClick={()=>void run(()=>account.signup(email,password),"account.signupSent")}>{t("account.signup")}</button></div><button className="reset-login" disabled={busy||!email} onClick={()=>void run(()=>account.reset(email),"account.resetSent")}>{t("account.reset")}</button>{message&&<p className="login-message" role="status">{message}</p>}<div className="local-option"><p>{t("account.localDescription")}</p><button onClick={onLocal}>{t("account.continueLocal")}</button></div></section></main>
}
