import { useState } from "react";
import { Cloud, LogIn, LogOut, RefreshCw } from "lucide-react";
import { useTranslation } from "react-i18next";
import { requestPasswordReset, resetPassword, signInEmail, signInGoogle, signOut, signUpEmail, type AuthUser } from "../lib/auth";
import type { SyncStatus } from "../lib/sync";

export function AccountSync({ user, status, lastSyncedAt, onAuthenticated, onSync, onLogout }:{ user:AuthUser|null;status:SyncStatus;lastSyncedAt:string|null;onAuthenticated:()=>Promise<void>;onSync:()=>Promise<void>;onLogout:()=>Promise<void> }) {
  const { t, i18n } = useTranslation();
  const params = new URLSearchParams(location.search);
  const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [name,setName]=useState(""); const [error,setError]=useState(params.has("authError")?t("account.oauthError"):""); const [notice,setNotice]=useState(""); const [busy,setBusy]=useState(false);
  const resetToken = params.get("token");
  async function act(action:()=>Promise<unknown>,authenticate=false){setBusy(true);setError("");setNotice("");try{await action();if(authenticate)await onAuthenticated()}catch(e){setError(e instanceof Error?e.message:t("account.error"))}finally{setBusy(false)}}
  return <section className="account-panel"><div className="account-heading"><Cloud size={24}/><div><h2>{t("account.title")}</h2><p>{t("account.description")}</p></div></div>
    {!user?<div className="account-form">{!resetToken&&<><label>{t("account.name")}<input autoComplete="name" value={name} onChange={e=>setName(e.target.value)}/></label><label>{t("account.email")}<input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label></>}<label>{resetToken?t("account.newPassword"):t("account.password")}<input type="password" autoComplete={resetToken?"new-password":"current-password"} value={password} onChange={e=>setPassword(e.target.value)}/></label><div className="account-actions">{resetToken?<button disabled={busy||!password} onClick={()=>void act(async()=>{await resetPassword(resetToken,password);history.replaceState({},"","/settings");setNotice(t("account.resetComplete"))})}>{t("account.savePassword")}</button>:<><button disabled={busy} onClick={()=>void act(signInGoogle)}><LogIn size={17}/>{t("account.google")}</button><button disabled={busy||!email||!password} onClick={()=>void act(()=>signInEmail(email,password),true)}>{t("account.signIn")}</button><button disabled={busy||!email||!password} onClick={()=>void act(()=>signUpEmail(name||email.split("@")[0],email,password),true)}>{t("account.signUp")}</button><button className="text-button" disabled={busy||!email} onClick={()=>void act(async()=>{await requestPasswordReset(email);setNotice(t("account.resetSent"))})}>{t("account.reset")}</button></>}</div></div>
    :<div className="account-session"><p><strong>{t("account.signedIn")}</strong> {user.email}</p><p>{t("account.status")}: <strong>{t(`account.states.${status}`)}</strong></p><p>{t("account.lastSync")}: {lastSyncedAt?new Intl.DateTimeFormat(i18n.language,{dateStyle:"medium",timeStyle:"short"}).format(new Date(lastSyncedAt)):t("account.never")}</p><div className="account-actions"><button disabled={status==="syncing"} onClick={()=>void onSync()}><RefreshCw size={17}/>{t("account.syncNow")}</button><button className="secondary" onClick={()=>void act(async()=>{await signOut();await onLogout()})}><LogOut size={17}/>{t("account.logout")}</button></div></div>}
    {notice&&<p role="status" className="backup-message success">{notice}</p>}{error&&<p role="alert" className="backup-message error">{error}</p>}</section>;
}
